'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel.DataAnnotations

Partial Public Class leave
    Public Property leave_id As Integer

    Public Property reason As String
    <DataType(DataType.Date)>
    Public Property start_date As Date

    <DataType(DataType.Date)>
    Public Property end_date As Date
    Public Property user_id As String

    Public Overridable Property leavestatus As ICollection(Of leavestatu) = New HashSet(Of leavestatu)

End Class

